### ISSUE TITLE
Create shop and add shop items

### ISSUE THREAD

**Issue by VelvetThePanda** [VelvetThePanda/Silk#11]
Leave a comment or create and issue and mention this for suggestions on what to add to the supposed shop.

**Comment by NatsumiHB** [comment]
Add a profile function and have people be able to buy badges or cool show-off items. See Mantaro and Tatsumaki for examples.

**Comment by VelvetThePanda** [comment]
> Add a profile function and have people be able to buy badges or cool show-off items. See Mantaro and Tatsumaki for examples.

Perhaps, but I'll have to look into some image APIs to get things in some sort of format/template lol.
