### ISSUE TITLE
X amount of money for creating a new economy account

### ISSUE THREAD

**Issue by tommyshelby9121** [VelvetThePanda/Silk#110]
It appears that users get an extra $300 when they create a new economy account using `>>daily` for a total of $500 which includes the current $200 daily amount. I would recommend just giving the user $300 saying "Since you're new, you get $300", this is related to Issue #109 and would work alongside it. So if you create an account using any of the user economy commands other than `daily` which are: `cash`, `donate`, and `shop` you'd just get the $300, however, if you run `daily` and create an economy account that way you get an extra $200 on top, as to how it is currently.

**Comment by VelvetThePanda** [comment]
So, worded in a better format, you're suggesting:

- Allow economy account to be created when any user uses an economy-related command
- Give $300 dollars when said command is run, but allot the extra $200 in the case of the daily command.
