### ISSUE TITLE
Perms command seems to be faulty

### ISSUE THREAD

**Issue by tommyshelby9121** [VelvetThePanda/Silk#113]
![image](https://user-images.githubusercontent.com/35604903/102921613-c5649b00-44e0-11eb-8b57-48c6a225c981.png)
As the image suggests I have the permission to kick, ban, and manage messages, which I was unable to do.

**Comment by VelvetThePanda** [comment]
You do not. This is in relation to Silk!'s own permissions on a guild, informing that certain commands require certain permissions to work properly.
