### ISSUE TITLE
Embed footer change

### ISSUE THREAD

**Issue by tommyshelby9121** [VelvetThePanda/Silk#115]
![image](https://user-images.githubusercontent.com/35604903/102921820-24c2ab00-44e1-11eb-9b16-d3bde16490bc.png)
According to the image, it only shows that the command was requested by an id. Instead of that, why not change it to the tag of the user, so it would be like so; `Requested By: Luci#9121`. In addition to this, why not change the footer image or icon to the avatar of the user who executed the command initially instead of the the avatar of the bot?

**Comment by VelvetThePanda** [comment]
Usernames can change at any moment, rendering any previous footer effectively worthless, however your account Id is a snowflake that persists for the lifetime of your account.

**Comment by tommyshelby9121** [comment]
> Usernames can change at any moment, rendering any previous footer effectively worthless, however your account Id is a snowflake that persists for the lifetime of your account.

Is that why the bot displays my nickname in one of the embeds?
![image](https://user-images.githubusercontent.com/35604903/102930589-d74e3a00-44f0-11eb-8c08-eff40308828b.png)

**Comment by VelvetThePanda** [comment]
Partly, yes.

**Comment by tommyshelby9121** [comment]
You say usernames can change at any moment, then why have my nickname, not username, in the embed?

**Comment by VelvetThePanda** [comment]
See my [comment on issue #116](https://github.com/VelvetThePanda/Silk/issues/116#issuecomment-749760482)
