### ISSUE TITLE
Uniformity among embeds

### ISSUE THREAD

**Issue by tommyshelby9121** [VelvetThePanda/Silk#116]
Just saw a couple of embeds that had footers and some that don't. And for the ones that did have footers, they were quite different. 
![image](https://user-images.githubusercontent.com/35604903/102922382-0f9a4c00-44e2-11eb-9a99-143e2719b20a.png)
![image](https://user-images.githubusercontent.com/35604903/102922399-14f79680-44e2-11eb-9966-693fb948613e.png)
![image](https://user-images.githubusercontent.com/35604903/102922413-1aed7780-44e2-11eb-9c6e-35ee6e0b3dee.png)
![image](https://user-images.githubusercontent.com/35604903/102922436-1fb22b80-44e2-11eb-950f-939c5e474ec5.png)
![image](https://user-images.githubusercontent.com/35604903/102922451-250f7600-44e2-11eb-8f4a-e8ad0576026e.png)

**Comment by VelvetThePanda** [comment]
We migrated away from using timestamps in embeds as they're listed in the message itself, however as Silk! grows, it becomes harder to remember all the embeds, but we'll work on this.

**Comment by VelvetThePanda** [comment]
Fixed in PR #125
