### ISSUE TITLE
Removed "?" after hoisted in role info embed

### ISSUE THREAD

**Issue by tommyshelby9121** [VelvetThePanda/Silk#117]
![image](https://user-images.githubusercontent.com/35604903/102922726-9cdda080-44e2-11eb-966a-dfee04d0f911.png)

**Comment by tommyshelby9121** [comment]
Also I would recommend removing the hoisted and mentionable ones and maybe inline some of them?

**Comment by VelvetThePanda** [comment]
Resolved.
