### ISSUE TITLE
Permission unfulfilled embed on certain commands

### ISSUE THREAD

**Issue by tommyshelby9121** [VelvetThePanda/Silk#120]
The `clean` command under the `General` category tells the user that they don't have specific permission for the command however, none of the other moderation commands or staff-only/admin-only commands don't tell you that you don't have permissions.

**Comment by VelvetThePanda** [comment]
Slight oversight in the system used to determine permissions and the response system. The clear command is attributed with `[RequireUserPermissions]`, whilst the other moderation commands are attributed with `[RequireFlag]`
