### ISSUE TITLE
Fix 'Do not use apk upgrade' issue in Silk.Core\Dockerfile

### ISSUE THREAD

**Issue by VelvetThePanda** [VelvetThePanda/Silk#122]
[CodeFactor](https://www.codefactor.io/repository/github/velvetthepanda/silk) found an issue: Do not use apk upgrade

It's currently on:
[Silk.Core\Dockerfile:13
](https://www.codefactor.io/repository/github/velvetthepanda/silk/source/development/Silk.Core/Dockerfile#L13)Commit d325ac682ffb5dc83d9eb376e712f895a2b67fbf

**Comment by NatsumiHB** [comment]
The issue is if we don't use it the bot won't work with Alpine, resulting in a 300MB+ Docker image as you need to manually upgrade OpenSSL.

So this is safe to ignore and might tell you why I don't use CodeFactor anymore ;).

**Comment by NatsumiHB** [comment]
You can however just remove the `-alpine` if you can live with such big images by going with something like Debian.

**Comment by VelvetThePanda** [comment]
It gave a suggestion of how to upgrade in unpriveleged container, unless you wanna make it privileged, idk. I don't docker :meowshrug:
