### ISSUE TITLE
Request money command

### ISSUE THREAD

**Issue by CalebABG** [VelvetThePanda/Silk#161]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
A request command to go along side the <prefix>donate | gift command, so a member can request money from another member

**Describe alternatives you've considered**
Implementation considerations / edge cases:
1. The member requesting needs to have or be setup with a economy user account (so they're in the db and can send or receive money)
2. The amount the member is requesting should be greater than $0 dollars (could be an Easter egg or something if they do request nothing 👍🏽)
3. The member the request is sent to can either accept or deny the money request
    - If they accept and the amount is greater than the users balance, send response saying they can't complete the transaction
    - If they accept and the amount is greater than $500 - $1000, issue a confirmation code to make sure they really do want to transfer so much
    - If they deny, then send response saying the payer denied sending the requested amount

**Additional context**

**Comment by VelvetToroyashi** [comment]
Might be wortwhile considering to make an economy service for this, really.

Maybe a Confirmation service, too. Don't want to over abstract, but the constantly repeating code is tedious to maintain.
