### ISSUE TITLE
Error msg on role not found

### ISSUE THREAD

**Issue by katnova** [VelvetThePanda/Silk#197]
**Is your feature request related to a problem? Please describe.**
`>>role акат` gives no error nor role (it contains characters, not in normal English LOCALE's).

**Describe the solution you'd like**
A message describing how to use the command on `>>role` (no args[]) in more detail (such as does the role need to already exist in the server, do you need to do `>>role @someRole` or can you just do `>>role someRole`, etc...)
An error message such as `role not foud` or `failed to assign role`, whatever is more applicable.

**Additional context**
![image](https://user-images.githubusercontent.com/49052296/110237205-d033a700-7ef7-11eb-9407-edd6ebf506d0.png)
![image](https://user-images.githubusercontent.com/49052296/110237226-f8bba100-7ef7-11eb-95d4-0a180c7cf399.png)

**Comment by VelvetToroyashi** [comment]
There is an oversight in the overall exception handling system, and I do need to rewrite it.

**Comment by VelvetToroyashi** [comment]
As you can see on [Lines 28-74](https://github.com/VelvetThePanda/Silk/blob/development/src/Silk.Core/Utilities/Bot/BotExceptionHandler.cs#L28-74), it is a basic switch expression that falls back on either sending the help message, or logging to the console.

**Comment by katnova** [comment]
Alright, Is this a "you should learn C to fork and fix it" situation?
(or did this issue just not get marked as complete?)
Tbh I have no intentions of using this software I just wanted to point out the UX issue.

**Comment by VelvetToroyashi** [comment]
As far as I'm aware without modifying commands and parsing things myself, the library does not give semantic information regarding type arguments.

**Comment by katnova** [comment]
Yikes. Well, I'll close this issue then until it's feasible in production.
