### ISSUE TITLE
Auto-deletion of scam links

### ISSUE THREAD

**Issue by matej118111** [VelvetThePanda/Silk#553]
I don't know if the bot has already this feature, but i will suggest it anyway. If the bot - sees any link from [this json file ](https://github.com/nikolaischunk/discord-phishing-links/blob/main/domain-list.json) it could automatically kick the user and delete the links.

**Comment by VelvetToroyashi** [comment]
Thank you for the issue! Silk can already detect phishing links via a special phishing gateway so links can be added and removed in real-time. You can find my websocket implementation [here](https://github.com/VTPDevelopment/Silk/blob/development/src/Silk.Core/Services/AutoModAntiPhisher.cs)
